<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class Model_blog extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

	// Get post by sr_no
	
   function get_post($blog_id)
   {
	   return $this->db->get_where('blog',array('blog_id'=>$blog_id))->row_array();
   }
    /*
     * Get blogs by user id
     */

    function getblogby_userid()
    {
        $user_id = $this->session->userdata('id');
        $sql = 'SELECT * FROM blog b 
		JOIN users u
        ON b.user_id = u.user_id
        WHERE b.user_id LIKE ? ORDER BY blog_id DESC';
        return $this->db->query($sql, [$user_id])->result_array();
    }
    /*
     * Get all blogs
     */
    function get_all_blog()
    {
        $sql = 'SELECT * FROM blog b 
		JOIN users u
        ON b.user_id = u.user_id
        ORDER BY blog_id DESC';
        return $this->db->query($sql)->result_array();
    }

    /*
     * function to add new blog
     */
    function add_blog($params)
    {
        $this->db->insert('blog', $params);
        return $this->db->insert_id();
    }

    // function to update a post

    function update_post($blog_id, $params)
    {
        $this->db->where('blog_id', $blog_id);
        return $this->db->update('blog', $params);
    }
	    
    /*
     * function to delete post
     */
	 function delete_post($blog_id)
	 {
		 return $this->db->delete('blog',array('blog_id'=>$blog_id));
	 }
}